import os
import time

os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 6 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 5 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 4 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 3 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 8 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 1 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 2 on")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 7 on")
time.sleep(2)

os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 6 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 5 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 4 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 3 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 8 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 1 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 2 off")
time.sleep(0.5)
os.system("/home/admin/8mosfet-rpi/8mosfet 0 write 7 off")
time.sleep(0.5)